# Press PVR key to activate this. If using an Arcam receiver connect Ugoos to the PVR HDMI port. 
#
# *********************************************************************************************************
#       this file is configuration for each factory remote device
#
# 	work_mode	  0 :software mode  1 :hardware mode
#	repeat_enable	  0 :disable repeat 1 :enable repeat
#
#	factory_code      each device has it's unique factory code.
#			  pattern:custom_code(16bit)+index_code(16bit)
#			  examble: 0xff000001 = 0xff00(custom cod)  0001 (index)
#
#	release_delay	  unit:ms.release will report from kernel to user layer after this period of time
#			  from press or repeat triggered.
#
#	debug_enable      0 :debug disable  1 :debug disable
#
# SW MODE:
#
#	bit_count	  how many bits in each frame
#	tw_leader_act	  time window for leader active
#	tw_bit0		  time window for bit0 time.
#	tw_bit1		  time window for bit1 time
#	tw_repeat_leader  time window for repeat leader
#
# REG
#
#	reg_base_gen	  set value for PREG_IR_DEC_BASE_GEN
#	reg_control	  set value for PREG_IR_DEC_CONTROL
#	reg_leader_act	  set value for PREG_IR_DEC_LEADER_ACTIVE
#	reg_leader_idle	  set value for PREG_IR_DEC_LEADER_IDLE
#	reg_repeat_leader set value for PREG_IR_DEC_REPEAT_IDLE
#	reg_bit0_time	  set value for PREG_IR_DEC_BIT0_TIME
#
# *********************************************************************************************************
#
# amlogic NEC remote  Arcam AVR31 PVR default (018)
#   
factory_code    = 0x31000001

work_mode       = 1
repeat_enable   = 1
repeat_delay    = 130
repeat_peroid   = 120
release_delay   = 20
debug_enable    = 1

key_begin

# Default: the volume keys are sent to the Arcam receiver.
# To send them to the device: press device key and 5 for 3s until the led is on. Press VOL UP. Press device key. Led blinks 3x.
# To send them to the receiver: press device key and 5 for 3s until the led is on. Press VOL UP. Press AMP. Led blinks 3x.
# This setting is only valid for this device key.
    0x1f 114 # KEY_VOLUMEDOWN
    0x40 115 # KEY_VOLUMEUP

    0x00 116	# KEY_POWER, define in Ugoos AM6B+ Android this remote key as additional Power On key.

    0x03 2	# KEY_1
    0x04 3	# KEY_2
    0x05 4	# KEY_3
    0x06 5	# KEY_4
    0x07 6	# KEY_5
    0x08 7	# KEY_6
    0x09 8	# KEY_7
    0x0a 9	# KEY_8
    0x0b 10	# KEY_9
    0x0c 11	# KEY_0
    0x43 23	# KEY_I Info

    0x65 168	# KEY_REWIND
    0x64 208	# KEY_FASTFORWARD
    0x4a 109	# KEY_PAGEDOWN Chapter -
    0x49 104	# KEY_PAGEUP   Chapter +
    0x63 128	# KEY_STOP
    0x60 207	# KEY_PLAY
    0x6c 119	# KEY_PAUSE
    0x61 167	# KEY_RECORD, remote key RECORD, mapped to Globalsearch+

    0x11 103	# KEY_UP
    0x12 105	# KEY_LEFT
    0x13 97 	# KEY_ENTER
    0x14 106	# KEY_RIGHT
    0x15 108	# KEY_DOWN
    0x1b 125	# KEY_MENU
    0x41 1	# KEY_BACK

    0x16 102	# KEY_HOME
    0x4b 24	# KEY_O, remote key DISP, Playerprocessinfo

#    0x1c 0x18e # KEY_RED, not unique in Keymap editor
#    0x1d 0x18f # KEY_GREEN, not unique in Keymap editor
#    0x1a 0x190 # KEY_YELLOW, not unique in Keymap editor
#    0x1e 0x191 # KEY_BLUE, not unique in Keymap editor
    0x1c 59	# KEY_F1, remote key RED, Dummy for mapping
    0x1d 60	# KEY_F2, remote key GREEN, Dummy for mapping
    0x1a 61	# KEY_F3, remote key YELLOW, Dummy for mapping
    0x1e 62	# KEY_F4, remote key BLUE, Dummy for mapping

key_end

repeat_key_begin

    0x1f 114 # KEY_VOLUMEDOWN
    0x40 115 # KEY_VOLUMEUP

    0x11 103 # KEY_UP
    0x12 105 # KEY_LEFT
    0x14 106 # KEY_RIGHT
    0x15 108 # KEY_DOWN

repeat_key_end
